services:
  - type: web
    name: tg-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /healthz
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE_NUMBER
        sync: false
